const express = require('express')
const router = express.Router()
const {uploadImageProduct} = require('../utils/multerConfig')
const authencationMiddleWare = require('../middlewares/authencationMiddleWare')
const ProductController = require('../controller/ProductController')
const {validateAddProduct, validateUpdateProduct} = require('../middlewares/ProductMiddleWare')
router.post('/add-product', uploadImageProduct.single('image'), validateAddProduct, ProductController.addProduct)
router.put('/update-product/:idProduct', uploadImageProduct.single('image'), validateUpdateProduct, ProductController.updateProduct)
router.delete('/delete-product/:idProduct', authencationMiddleWare, ProductController.deleteProduct)
router.get('/get-all-product', ProductController.getAllProduct)
router.get('/detail-product/:idProduct', ProductController.getDetailProduct)
router.get('/price', ProductController.getPrice)
router.get('/search-product', ProductController.searchProduct)
module.exports = router
